# Generated by Django 3.2.3 on 2021-06-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=50)),
                ('taskDis', models.TextField()),
                ('taskTime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
